### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by 7elix** [sclable/xml-lint#19]
**Support PHP version ^8.0.**
Loosen composer constraints

**Comment by m-bymike** [comment]
Thank your request, I'll take care of it as soon as possible!

**Comment by 7elix** [comment]
Thank you!

We already upgraded our automated testing suite to php 8.9.
Works well without further code changed.

**Comment by 7elix** [comment]
🙇🏻  Thank You Very Much!
