### ISSUE TITLE
Add support for Symfony 6.0

### ISSUE THREAD

**Issue by xvilo** [sclable/xml-lint#21]
Symfony version 6.0 is freshly released and this library does not yet seem to support this new version. Would be great if somebody could verify it's compatibility and create a new release 👍 

Currently don't have the time to do it myself, but maybe we'll be there sometime. For now creating this issue to keep track of the problem

**Comment by m-bymike** [comment]
Hi, thank you for creating the ticket. It's the same problem for me at the moment, time's limited...
